2019-11-28 13:19:09,507 ERROR: Exception on /explore [GET] [in /home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ubuntu/blog/app/main/routes.py", line 59, in explore
    prev_url=prev_url)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/blog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/ubuntu/blog/app/templates/index.html", line 17, in root
    <nav aria-label="...">
  File "/home/ubuntu/blog/app/templates/base.html", line 14, in root
    {% block styles %}
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block_doc
    {% block body -%}
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 39, in block_html
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 92, in block_body
  File "/home/ubuntu/blog/app/templates/base.html", line 121, in block_content
    xhr = null;
  File "/home/ubuntu/blog/app/templates/index.html", line 43, in block_app_content
  File "/home/ubuntu/blog/app/templates/_post.html", line 18, in root
    <br>
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 630, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'avatar'
2019-11-28 13:42:47,269 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 13:43:39,115 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 13:44:17,702 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 13:47:57,101 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 13:49:18,407 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 13:49:40,108 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 13:49:53,998 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 13:50:21,478 ERROR: Exception on /admin/ [GET] [in /home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_admin/model/base.py", line 1943, in index_view
    delete_form = self.delete_form()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_admin/model/base.py", line 1357, in delete_form
    return self._delete_form_class()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_admin/form/__init__.py", line 16, in __init__
    super(BaseForm, self).__init__(formdata=formdata, obj=obj, prefix=prefix, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/wtforms/form.py", line 272, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/wtforms/form.py", line 52, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/wtforms/meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/wtforms/fields/core.py", line 353, in bind
    return self.field_class(*self.args, **kw)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/wtforms/fields/core.py", line 110, in __init__
    self.label = Label(self.id, label if label is not None else self.gettext(_name.replace('_', ' ').title()))
  File "/home/ubuntu/.local/lib/python3.7/site-packages/wtforms/fields/core.py", line 166, in gettext
    return self._translations.gettext(string)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_admin/babel.py", line 55, in gettext
    t = wtforms_domain.get_translations()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_babelex/__init__.py", line 510, in get_translations
    locale = get_locale()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_babelex/__init__.py", line 224, in get_locale
    locale = babel.load_locale(rv)
AttributeError: 'Babel' object has no attribute 'load_locale'
2019-11-28 13:51:11,682 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 13:58:53,909 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 14:04:39,593 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 14:15:57,988 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 14:16:21,798 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 14:16:45,995 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 14:17:39,270 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 14:32:11,115 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
